config/routes.rb
Warehouse::Application.routes.draw do

  root to: 'items#index'
  get '/logs', to: 'users#logs'
  get '/items_logs', to: 'items#logs'

  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :connection_logs, only: [:index]
  resources :items

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :user
  has_many :connection_logs

  after_create :log_connection

  SESSION_LENGTH = 1.minute

  scope :active, -> { where(active: true) }

  def expired?
    Time.now.minus_with_coercion(last_activity).round > SESSION_LENGTH
  end

  def kill
    if active == true
      update_attribute(:active, false)
      ConnectionLog.create(connection_id: id, user_id: user_id, category: ConnectionLog::KILLED)
    end
  end

  private

    def log_connection
      ConnectionLog.create(connection_id: id, user_id: user_id, category: ConnectionLog::LOGGED_IN)
    end
end

app/models/connection_log.rb
class ConnectionLog < ActiveRecord::Base

  LOGGED_IN = 1
  LOGGED_OUT = 2
  EXPIRED = 3
  KILLED = 4

  CATEGORIES = {
    1 => 'logged in',
    2 => 'logged out',
    3 => 'expired',
    4 => 'killed'
  }

  belongs_to :connection
  belongs_to :user

  def category_name
    CATEGORIES[category]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  CHAIR = 1
  TABLE = 2
  WINDOW = 3
  DOOR = 4

  CATEGORIES = {
    1 => "chair",
    2 => "table",
    3 => "window",
    4 => "door"
  }

  has_paper_trail on: [:update], only: [:status]

  validates :name, :status, :critical_level, :category, presence: true

  validates :status, :critical_level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :check_critical_level

  def category_name
    CATEGORIES[category]
  end

  private
    def check_critical_level
      if status <= critical_level
        AlertMailer.send_alert(self).deliver
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :connections
  has_many :connection_logs

  def c_name
    "connection_user_#{id}"
  end
  def active_connection
    connections.active.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_connection
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def current_user_connection
    if current_user
      @current_user_connection ||= Connection.find(session[current_user.c_name])
    end
  end

  def require_current_user
    if current_user
      # assuming current_connection always exists alongside current_user
      if current_user_connection.active?
        unless current_user_connection.expired?
          current_user_connection.update_attribute(:last_activity, DateTime.now)
        else
          ConnectionLog.create(connection_id: current_user_connection.id, user_id: current_user.id, category: ConnectionLog::EXPIRED)
          current_user_connection.update_attribute(:active, false)
          session[:user_id] = nil

          redirect_to new_user_session_path, alert: "You were automatically logged out due to inactivity. Login required"
        end
      else
        session[:user_id] = nil

        redirect_to new_user_session_path, alert: "Login on different machine detected. Login required"
      end
    else
      redirect_to new_user_session_path, alert: "Login required"
    end
  end

end

app/controllers/connection_logs_controller.rb
class ConnectionLogsController < ApplicationController
  def index
    @connection_logs = ConnectionLog.order('created_at DESC')
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_current_user

  def index
    if params[:sort]
      @items = Item.order(params[:sort])
    else
      @items = Item.all
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new item_params
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update item_params
      redirect_to items_path
    else
      render :edit
    end
  end

  def logs
    @versions = PaperTrail::Version.order('created_at DESC')
  end

  private

    def item_params
      params.require(:item).permit(:name, :description, :status, :critical_level, :category)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(email: params[:email]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id

      if session[user.c_name]
        if user.active_connection && (user.active_connection.id != current_user_connection.id)
          user.active_connection.kill
        end

        current_user_connection.update_attributes(active: true, last_activity: DateTime.now)
        ConnectionLog.create(connection_id: current_user_connection.id, user_id: user.id, category: ConnectionLog::LOGGED_IN)
      else
        user.active_connection.kill if user.active_connection
        connection = user.connections.create(active: true, last_activity: DateTime.now)
        session[user.c_name] = connection.id
      end

      redirect_to items_path
    else
      flash[:alert] = 'Wrong credentials'
      render :new
    end
  end

  def destroy
    current_user_connection.update_attribute(:active, false)
    ConnectionLog.create(connection_id: current_user_connection.id, user_id: session[:user_id], category: ConnectionLog::LOGGED_OUT)
    session[:user_id] = nil

    redirect_to new_user_session_path, alert: "You've been successfuly logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def logs
  end

  def destroy
    user = User.find(params[:id])
    user.destroy

    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def flash_message(name)
    if flash[name]
      content_tag :div, flash[name], class: "alert alert-danger"
    end
  end
end

app/helpers/connection_logs_helper.rb
module ConnectionLogsHelper
end

app/helpers/items_controller_helper.rb
module ItemsControllerHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/connection_logs/index.html.erb
<h1>Connection logs</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Connection ID</th>
      <th>Action</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @connection_logs.each do |connection_log| %>
      <tr>
        <td><%= connection_log.user.email %></td>
        <td><%= connection_log.connection_id %></td>
        <td><%= connection_log.category_name %></td>
        <td><%= connection_log.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/_edit_form.html.erb
<%= render "shared/errors", object: @item %>

<%= form_for @item do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field :status, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :critical_level %>
    <%= f.text_field :critical_level, class: "form-control", disabled: true %>
  </div>
  
  <%= f.submit 'Save item' %>
<% end %>

app/views/items/_form.html.erb
<%= render "shared/errors", object: @item %>

<%= form_for @item do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field :status, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :critical_level %>
    <%= f.text_field :critical_level, class: "form-control" %>
  </div>

    <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, Item::CATEGORIES.invert, class: "form-control" %>
  </div>

  <%= f.submit 'Save item' %>
<% end %>

app/views/items/edit.html.erb
<h2>Edit item</h2>

<%= render 'edit_form' %>

app/views/items/index.html.erb
<h1>Items</h1>
<p><%= link_to 'Create item', new_item_path, class: "btn btn-primary" %>
<%= link_to 'View item logs', '/items_logs', class: "btn" %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th><%= link_to 'Category', sort: 'category' %></th>
      <th>Description</th>
      <th><%= link_to 'Status', sort: 'status' %></th>
      <th>Critical level<th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.category_name %></td>
        <td><%= item.description %></td>
        <td><%= item.status %></td>
        <td><%= item.critical_level %></td>
        <td>
          <%= link_to 'Edit', edit_item_path(item), class: "btn btn-default" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/logs.html.erb
<h1>Item logs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Item name</th>
      <th>User</th>
      <th>Amount</th>
      <th>+/-</th>
      <th>Date<th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.item.name %></td>
        <td><%= User.find(version.whodunnit.to_i).email %></td>
        <% if version.next %>
          <% diff = version.object[version.object.index("status: ")+8..version.object.index("\ncritical")].to_i - version.next.item.status %>
          <% if diff < 0 %>
            <td><%= diff.abs %></td>
            <td>-</td>
          <% else %>
            <td><%= diff %></td>
            <td>+</td>
          <% end %>
        <% else %>
          <% diff = version.item.status - version.object[version.object.index("status: ")+8..version.object.index("\ncritical")].to_i %>
          <% if diff < 0 %>
            <td><%= diff.abs %></td>
            <td>-</td>
          <% else %>
            <td><%= diff %></td>
            <td>+</td>
          <% end %>
        <% end %>
        <td><%= version.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<h2>Create item</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Warehouse</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta charset="utf-8">
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="header">
    <div class="container">
      <h1 class="site-name"><%= link_to "Warehouse", root_path %></h1>
        <% if current_user %>
          <ul class="nav nav-pills pull-left">
            <% if false %>
              <li class="<%= "active" if current_page?(root_path) %>"><%= link_to "Domov", root_path %></li>
              <li class="<%= "active" if current_page?(groups_path) %>"><%= link_to "Moje triedy", groups_path %></li>
            <% end %>
          </ul>

          <ul class="nav nav-pills pull-right">
            <li><%= link_to current_user.email, '#' %></li>
            <li><%= link_to "Log out", user_session_path(1), method: :delete %></li>
          </ul>
        <% end %>
    </div>
  </div>

  <div class="main">
    <div class="container">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      Form errors
    </div>

    <div class="panel-body">
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>User login</h1>

<%= flash_message(:alert) %>

<%= form_tag user_sessions_path do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= text_field_tag :email, nil ,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, class: "form-control" %>
  </div>

  <%= submit_tag 'Log in', class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", object: @user %>

<%= form_for @user do |f| %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit 'Create' %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<p><%= link_to 'Create user', new_user_path, class: "btn btn-primary" %>
<%= link_to 'View connection logs', connection_logs_path, class: "btn" %></p>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Delete', user_path(user), data: {confirm: "Are you sure?"}, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/logs.html.erb
<h2><%= link_to 'Connection logs', connection_logs_path %></h2>
<h2><%= link_to 'Item logs', 

app/views/users/new.html.erb
<h2>Create user</h2>

<%= render 'form' %>